<?php $CI =& get_instance(); $isAdmin = $CI->session->userdata('role') === 'admin'; ?>
<div class="d-flex justify-content-between align-items-center mb-3 no-print">
    <a href="<?= base_url($isAdmin ? 'admin_payments/history' : 'payments') ?>" class="back-link">&larr; <?= $isAdmin ? 'Payment history' : 'My payments' ?></a>
    <button type="button" class="btn btn-primary" onclick="window.print()"><?= icon('file', 16) ?> Print / Save as PDF</button>
</div>

<div class="receipt card mx-auto">
    <div class="receipt-head">
        <div class="d-flex align-items-center gap-2">
            <span class="brand-mark">TC</span>
            <div><div class="fw-bold">Theological Center</div><small class="text-muted">Learning Portal</small></div>
        </div>
        <div class="text-end">
            <div class="receipt-label">Official receipt</div>
            <div class="receipt-no"><?= receipt_no($r['id']) ?></div>
        </div>
    </div>

    <div class="receipt-paid">
        <span class="stat-icon bg-soft-green"><?= icon('check', 22) ?></span>
        <div>
            <div class="receipt-amount"><?= money($r['amount']) ?></div>
            <div class="text-muted small">Paid by <?= $r['method'] === 'ecocash' ? 'EcoCash' : 'bank transfer' ?> &middot; approved <?= html_escape(date('j F Y', strtotime($r['reviewed_at']))) ?></div>
        </div>
    </div>

    <dl class="facts receipt-facts">
        <dt>Received from</dt><dd><?= html_escape($r['student_name']) ?><?= ! empty($r['student_id_number']) ? ' <span class="id-chip">' . html_escape($r['student_id_number']) . '</span>' : '' ?><br><small class="text-muted"><?= html_escape($r['student_email']) ?></small></dd>
        <dt>For</dt><dd><?= html_escape($r['course_name']) ?><?= $r['duration_text'] ? ' <span class="text-muted">(' . html_escape($r['duration_text']) . ')</span>' : '' ?></dd>
        <dt>Proof submitted</dt><dd><?= html_escape(date('j F Y, H:i', strtotime($r['submitted_at']))) ?></dd>
        <dt>Verified by</dt><dd><?= html_escape($r['approved_by'] ?: 'Administrator') ?></dd>
    </dl>

    <p class="receipt-foot">This receipt was generated by the Theological Center Learning Portal and confirms that the payment above was verified and approved. Keep it for your records.</p>
</div>
