<?php $CI =& get_instance(); $isAdmin = $CI->session->userdata('role') === 'admin'; ?>
<div class="d-flex justify-content-between align-items-center mb-3 no-print">
    <a href="<?= base_url($isAdmin ? 'admin_payments/history' : 'payments') ?>" class="back-link">&larr; <?= $isAdmin ? 'Payment history' : 'My payments' ?></a>
    <button type="button" class="btn btn-primary" onclick="window.print()"><?= icon('file', 16) ?> Print / Save as PDF</button>
</div>

<div class="receipt card mx-auto">
    <div class="receipt-head">
        <?php
            $orgAddr = array_filter([setting('org_address'), setting('org_city'), setting('org_country')]);
            $orgCont = array_filter([setting('org_phone'), setting('org_email')]);
        ?>
        <div class="d-flex align-items-start gap-2 min-w-0">
            <span class="brand-mark"><?= html_escape(setting('org_initials', 'TC')) ?></span>
            <div class="min-w-0">
                <div class="fw-bold"><?= html_escape(setting('org_name', 'Theological Center')) ?></div>
                <?php if ($orgAddr): ?><small class="text-muted d-block"><?= html_escape(implode(', ', $orgAddr)) ?></small><?php endif; ?>
                <?php if ($orgCont): ?><small class="text-muted d-block"><?= html_escape(implode(' · ', $orgCont)) ?></small><?php endif; ?>
                <?php if (setting('org_registration_no')): ?><small class="text-muted d-block">Reg. no. <?= html_escape(setting('org_registration_no')) ?></small><?php endif; ?>
            </div>
        </div>
        <div class="text-end">
            <div class="receipt-label">Official receipt</div>
            <div class="receipt-no"><?= receipt_no($r['id']) ?></div>
        </div>
    </div>

    <div class="receipt-paid">
        <span class="stat-icon bg-soft-green"><?= icon('check', 22) ?></span>
        <div>
            <div class="receipt-amount"><?= money($r['amount']) ?></div>
            <div class="text-muted small">Paid by <?= $r['method'] === 'ecocash' ? 'EcoCash' : 'bank transfer' ?> &middot; approved <?= html_escape(date('j F Y', strtotime($r['reviewed_at']))) ?></div>
        </div>
    </div>

    <dl class="facts receipt-facts">
        <dt>Received from</dt><dd><?= html_escape($r['student_name']) ?><?= ! empty($r['student_id_number']) ? ' <span class="id-chip">' . html_escape($r['student_id_number']) . '</span>' : '' ?><br><small class="text-muted"><?= html_escape($r['student_email']) ?></small></dd>
        <dt>For</dt><dd><?= html_escape($r['program_name']) ?><?= $r['duration_text'] ? ' <span class="text-muted">(' . html_escape($r['duration_text']) . ')</span>' : '' ?></dd>
        <dt>Proof submitted</dt><dd><?= html_escape(date('j F Y, H:i', strtotime($r['submitted_at']))) ?></dd>
        <dt>Verified by</dt><dd><?= html_escape($r['approved_by'] ?: 'Administrator') ?></dd>
    </dl>

    <p class="receipt-foot"><?= html_escape(setting('receipt_footer', 'Thank you. Please keep this receipt for your records.')) ?>
        This receipt was generated by the <?= html_escape(setting('org_short_name', 'Theological Center')) ?> portal and confirms the payment above was verified and approved.</p>
</div>
